# Generated by Django 5.2.17 on 2026-09-15 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlanArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.JSONField(blank=True, null=True)),
                ('timeline', models.JSONField(blank=True, null=True)),
                ('events', models.JSONField(blank=True, default=list)),
                ('replans', models.JSONField(blank=True, default=list)),
                ('timeline_history', models.JSONField(blank=True, default=list)),
                ('booking_state', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(default='new_plan', max_length=32)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '历史规划归档',
                'verbose_name_plural': '历史规划归档',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['user', '-archived_at'], name='api_trippla_user_id_581eb8_idx')],
            },
        ),
    ]
